# Build Workflow

name: Build

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"

    strategy:
      matrix:
        version:
          ["1.8.9-forge"]

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Gradle Wrapper Validation"
        uses: gradle/wrapper-validation-action@v1

      - name: "Setup Java"
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Cache Gradle"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v1-jdk17-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: "Chmod Gradle"
        run: chmod +x ./gradlew


      - name: "Setup Gradle"
        run: ./gradlew setupGradle


      - name: "Build"
        run: ./gradlew build

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.version }} Artifacts
          path: versions/${{ matrix.version }}/build/libs/
